apiVersion: apps/v1
kind: Deployment
metadata:
  name: count-app-deployment
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: count
  template:
    metadata:
      labels:
        app: count
    spec:
      containers:
      - name: count
        image: israelfrank/webapp
        ports:
        - containerPort: 80
